markdown: redcarpet
pygments: true
permalink: /:categories/:title/

redcarpet: 
  extensions:
   - tables
   - no_intra_emphasis
   - autolink
   - superscript
   - strikethrough

pagination: true
paginate: 5

exclude:
  - "*.branches"
  - "*.kml"
  - "*.log"
  - "*.nb"
  - "*.trees"
  - "*.xml"
  - "*.cpp"
  - "*.h"
  - "*.hh"
  - "*.java"
  - "*.jar"
  - "*.csv"
  - "*.tsv"
  - "*.txt"
  - "*.rb"
  - "*.py"
  - "*.class"
  - "*.tips"
  - "*.fasta"
  - "*.nex"
  - "Gemfile"
  - "Gemfile.lock"

projects:
  - trvrb/coaltrace
  - trvrb/stem
  - trvrb/PACT
  - trvrb/dynamics-practical
  - trvrb/antigen
  - trvrb/haplotypes
  - trvrb/divergence
  - trvrb/ancestry
